Selected words transrate
skanehira/translate.vim pull request #6
Opened 2019-11-09 04:11 UTC by tamago324

Thank you for good plugin!

This pull requests includes:
* Made the selected word translatable
* Add key mapping

Please review

2019-11-09 04:14 UTC, tamago324 commented
日本語で書いてよかったんですね...

* 選択している単語を翻訳できるようにしました。
* キーマッピングを追加しました。

また、`g:translate_no_mappings` の初期値が `0` になっていますが、`1` でも構いません。
ゴリラさんの思想にあっている方に修正していただいて構いません。

2019-11-09 04:37 UTC, tamago324 commented
vim-surround のソースコードを参考にしました
https://github.com/tpope/vim-surround/blob/fab8621670f71637e9960003af28365129b1dfd0/plugin/surround.vim#L495

2019-11-10 07:19 UTC, skanehira requested changes
@tamago324 PRありがとうございます！
うれぴっぴ

コメントしたので、確認お願いします〜

2019-11-10 07:19 UTC, skanehira commented on autoload/translate.vim
> +        let text = getline(a:start, a:end)
`else`を追加した意図ってありますか？

2019-11-10 07:19 UTC, skanehira commented on autoload/translate.vim
> +    return text
最後に`join()`で改行で結合する必要があると思います。

2019-11-10 07:21 UTC, skanehira commented on plugin/translate.vim
> +endif
プラグインではキーマッピングを用意せず、`<Plug>`だけ定義してユーザに任せるという方針です。
なるべく本体の処理を簡易化したいためです。

2019-11-10 10:43 UTC, tamago324 commented on autoload/translate.vim
> +        let text = getline(a:start, a:end)
https://github.com/skanehira/translate.vim/blob/fae017e7ef0747a1553728cafc0779e188d9a22b/autoload/translate.vim#L62-L73

L63 で `text` に代入しているのですが、`a:args` が 空ではなかった場合、L64-L66 で `text` を上書きしていたため、 `else` を入れました
結果には影響しないため、もとの実装に戻したほうがよろしいでしょうか？

2019-11-10 10:43 UTC, tamago324 commented on autoload/translate.vim
> +    return text
help を見たところ、以下のように書いてありました。
* `getreg({regname})`:文字列が返される
* `getreg({regname}, 1, 1)` : リストが返される

そのため、`join()` しなくても良さそうですかね (help を再確認して、文字列で返されることに気づいた...)

2019-11-10 10:43 UTC, tamago324 commented on plugin/translate.vim
> +endif
了解です🙆‍♂ 
キーマッピングは削除しておきます

2019-11-10 11:13 UTC, skanehira commented on autoload/translate.vim
> +        let text = getline(a:start, a:end)
はい、分岐を増やしたくないので先に`getline()`したという感じです。
なので改善されるわけではないので、元の実装でお願いします〜

2019-11-10 12:06 UTC, tamago324 commented on autoload/translate.vim
> +        let text = getline(a:start, a:end)
了解です🙆‍♂

2019-11-11 05:35 UTC, skanehira commented on autoload/translate.vim
> +    return text
なるほどー

`join()`の目的は、外部コマンド`gtran`に引数として渡すときに、OSにあった改行コードを含める必要があるからです。
なので、`getreg({regname}, 1, 1)`でリストで取得して`join()`しないと意図した動きにならないと思っています。

実際動作は問題なかったんですか？

2019-11-11 07:40 UTC, tamago324 commented on autoload/translate.vim
> +    return text
今、確認したところ、行選択したときの挙動がおかしかったですね...
ですので、`getreg({regname}, 1, 1)` として `join()` するように修正しました！

2019-11-11 08:23 UTC, skanehira approved these changes
OKです〜

2019-11-11 08:23 UTC, merged

2019-11-11 08:23 UTC, skanehira commented
マージしました
PRありがとうございます！

2019-11-11 08:43 UTC, tamago324 commented
マージありがとうございます！！！